### ISSUE TITLE
Of samtools, bcftools and htslib

### ISSUE THREAD

**Issue by teepean** [WGSExtract/WGSExtract-Dev#1]
Hello!

I just wanted to mention that samtools, bcftools and htslib can be compiled from source without patches on Cygwin and MSYS2/MinGW. MSYS2/MinGW should be preferred as the result is native Windows application and has faster I/O operations.

**Comment by RandyHarr** [comment]
Hey Teepean, Marko has mentioned of your help before. Thanks for reaching out. And for reviving BAM Analysis Kit. Some great work by Felix that was ahead of its time.

Yes, I found compiling ver 1.10 easy on Cygwin. But thought I found the MinGW versions I tried still more buggy than Cygwin64 ones. Did not find them faster though (although Marko's old, released ones did exhibit that). Will check again. We have BWA and other tools added now as well. And still rely on some *Nix tools in the Win10 release to support some scripts (albeit they are quickly being removed).

Are you a Pythonic hacker? Want to join the project? I still have to get the reworked WGSE checked in but we are pushing for a new release that no longer requires us redistrubiuting reference genomes and similar (so you can be released on Github directly). If interested, join this project and I will work to get the code checked in so we can all start co-developing better. Have modularized the code and even suggested Marko make his microarray file capability more standalone. As that seems to be the biggest and most unique contribution.  FYI, my direct email is r @n dy at my cuz d0t us.

**Comment by teepean** [comment]
Hi Randy.

I would like to join the project! Although I have only recently started with Python but I do have knowledge in the rest of areas. 

BAM Analysis Kit is a great tool but it has it's shortcomings and improving it further has proved to be difficult and at it's current form it is not suitable for paired end data.
