### ISSUE TITLE
MyHeritage doesn't accept the converted file

### ISSUE THREAD

**Issue by iliakan** [WGSExtract/WGSExtract-Dev#10]
Tried to convert from CRAM to microarray RAW.

MyHeritage says "The file you have uploaded is in a format that we do not currently support. We are working to add support for this file type soon and will notify you by email once your results are ready."

Tried Combined, 23andme and MyHeritage formats, all the same.

**Comment by RandyHarr** [comment]
MyHeritage, FamilyTreeDNA and LivingDNA will not accept the CombinedKit.  No vendor will accept their own format file. 

CombinedKit is most useful for GEDMatch and Geneanet.  Most will accept 23andMe v3 and v5.  And usually Ancestry although FTDNA and sometimes MyHeritage get into problems every so often for a few weeks before they fix something they broke. Sometimes, MyHeritage and FTDNA get into funny modes and only accept each others kits.  In that case, an FTDNA file for loading to MyHeritage may work well. As far as we know, FTDNA still processes MyHeritage DNA test kits. 

I have uploaded 30+ kits to MyHeritage. Some Ancestry but most 23andMe (including v4).  But some have experienced sporadic stoppages by them from even direct test 23andMe and Ancestry files; not generated.  Our generated files are identical to what the vendor supplies sans the date code in the header -- the date code is constant in our files to date and could be used as a way to identify them.  Our hope is they never resort to that.  If we put another date in that is different for every kit, then they are imperceptible from the company generated files.

If you started with a CRAM, I am presuming you started with a Nebula file in Build 38.  That is not an issue. The tool applies liftover to the result to make it in Build 37 format which is what all vendors supply and accept.

I just uploaded an Ancestry v2 and 23andMe v5 generated kits without issue. Of course, they may still reject them in the next few days. But usually not. I also uploaded a generated kit I had previously uploaded.  They recognized that right away and suggested I cancel the upload.

Much of this is explained in the manual in the sections describing microarray file generation.  But it is a constantly changing picture (not generated files but microarray files in general) for reasons unknown with some of the vendors.

Please let us know if you continue to have issues.  I will close the issue for now but reopen if still not resolved.

**Comment by gecube** [comment]
It is no more an issue because MyHeritage stopped to accept foreign kits:

https://www.myheritage.com/dna/upload/OYYV7EYAWT6GIXIECIGV6LLHIBMCWVI

<img width="2558" height="1276" alt="Image" src="https://github.com/user-attachments/assets/ebc876dd-cd6a-4e8c-8bba-c0a07b7608c0" />
