### ISSUE TITLE
Can't download reference genome files

### ISSUE THREAD

**Issue by iammickeymac** [WGSExtract/WGSExtract-Dev#7]
Mac mini M1 running Monterey 12.3.1, Python Tcl 8.6 & Tk 8.6 (8.6.8), WGS Extract Beta ver3 (10 July 2021)

<img width="578" alt="screenshot_324" src="https://user-images.githubusercontent.com/77935051/161475898-e3aadd59-7dbb-419a-94de-616cae6612c8.png">

Michael

**Comment by RandyHarr** [comment]
Michael, it is fixed in the alpha v4 release.  As you are a member of that early access group, could you simply update to the alpha v4 to resolve this issue.  Thank you.

**Comment by iammickeymac** [comment]
Thank you Randy! 😁
I am working until the weekend but will jump on it first thing
Michael
