### ISSUE TITLE
Run without installer on Windows?

### ISSUE THREAD

**Issue by rjsdotorg** [WGSExtract/WGSExtract-Dev#9]
As a Python programmer I have the latest Python , and Java as well.
Is there a way to run the main script(s) from WGSExtract-Dev-master\program?
I'd like to try it to convert my Nebula to a format MyHeritage can digest...

**Comment by RandyHarr** [comment]
We have not checked any of the v4 code into GitHub. The release has all the source code in it though. 

Best thing is to download the installer and look at its scripts. It is not enough (on windows) to have python installed. It has to be able to run integrated with the cygwin executables; especially the 20+ bioinformatic tools we deliver with the cygwin environment. 

We would like to avoid the windows installation all together. It is the most complicated, troublesome, and difficult to maintain. But probably 1/2 the users are on windows. Once off Windows directly, we could likely become a bioconda release. 

With Win11 comes WSLG (GUI / graphical WSL). Recently, with fixes to the tcl/tk libraries and improved files system performance, WGS Extract can run better on Ubuntu Desktop in WSLG than on native windows. After all, most tools are developed on Linux systems. You do have to find the WSL installation to let Ubuntu really make use of your multiple cores and disk bandwidth and memory. 

Currently, the need for Java is very limited. Haplogrep only until recently. FastQC, VariantQC, GATK, etc more recently. We actually have to install jre8 and jre17 as different jar files require different versions. We try to determine if one is on the path and which one. So we only have to install the other.

We have had a request for a CLI access / server Edition of WGS Extract and it's microarray generator. But have not made much progress towards that.

If this answers your question, let us know so we can close the issue.

**Comment by rjsdotorg** [comment]
Good information, thanks.
I can try it on a Py4 easier than the Win7 install which failed due to paths, cygwin etc.
By all means, close.
